name: CI

on:
  push:
    branches:
      - master
      - feature
  pull_request:
    branches:
      - master
      - feature

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build React test image
        run: docker build -t vishalsharma369/react-test -f ./client/Dockerfile.dev ./client

      - name: Run tests
        run: docker run -e CI=true vishalsharma369/react-test npm test

      - name: Build client image
        if: success()
        run: docker build -t vishalsharma369/multi-client ./client

      - name: Build nginx image
        if: success()
        run: docker build -t vishalsharma369/multi-nginx ./nginx

      - name: Build server image
        if: success()
        run: docker build -t vishalsharma369/multi-server ./server

      - name: Build worker image
        if: success()
        run: docker build -t vishalsharma369/multi-worker ./worker

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        if: success()
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_ID}" --password-stdin

      # Push Docker images to Docker Hub
      - name: Push client image
        if: success()
        run: docker push vishalsharma369/multi-client

      - name: Push nginx image
        if: success()
        run: docker push vishalsharma369/multi-nginx

      - name: Push server image
        if: success()
        run: docker push vishalsharma369/multi-server

      - name: Push worker image
        if: success()
        run: docker push vishalsharma369/multi-worker
